export const FMS_TABS = [
  {
    key: "step1",
    label: "Step 1",
    badge: 52,
    header: "ORDER ENTRY",
    columns: [
      { key: "Timestamp", label: "Timestamp" },
      { key: "PONumber", label: "PO Number" },
      { key: "Date", label: "Date" },
      { key: "Yard", label: "Yard" },
      { key: "Org", label: "Org" },
      { key: "Item", label: "Item" },
      { key: "Qty", label: "Qty" },
      { key: "Delivery", label: "Delivery" },
      { key: "Company", label: "Company" },
      { key: "UID", label: "UID" },
      { key: "LeadDays", label: "	Lead Days" },
      { key: "status", label: "Status" },
      { key: "action", label: "Action" },
    ],
    data: [
      {
        Timestamp: "13/11/2024 10:59 AM",
        PONumber: "6700007894",
        Date: "27/10/2023",
        Yard: "",
        Org: "GRSE",
        Item: "Calibration Certificate",
        Qty: "1",
        Delivery: "26/02/2024",
        Company: "KS",
        UID: "Order-115	",
        LeadDays: "120",
        status: "NOT DONE",
        action: "Action",
      },
      {
        Timestamp: "14/11/2024 11:00 AM",
        PONumber: "6700007895",
        Date: "28/10/2023",
        Yard: "",
        Org: "GSL",
        Item: "MTC_ INDIAN / WORLD ME...",
        Qty: "4",
        Delivery: "27/02/2024",
        Company: "AE",
        UID: "Order-114",
        LeadDays: "120",
      },
      {
        Timestamp: "15/11/2024 12:00 PM",
        PONumber: "6700007896",
        Date: "29/10/2023",
        Yard: "",
        Org: "GSL",
        Item: "MTC_Indian / Worid Met",
        Qty: "5",
        Delivery: "2/12/2024",
        Company: "KS",
        UID: "Order-117	",
        LeadDays: "120",
      },
      {
        Timestamp: "16/11/2024 09:30 AM",
        PONumber: "6700007897",
        Date: "30/10/2023",
        Yard: "",
        Org: "GRSE",
        Item: "Gas Cylinders -5 Kgs",
        Qty: "8",
        Delivery: "26/02/2024",
        Company: "AE",
        UID: "Order-110",
        LeadDays: "120",
      },
      {
        Timestamp: "17/11/2024 03:45 PM",
        PONumber: "6700007898",
        Date: "31/10/2023",
        Yard: "",
        Org: "GRSE",
        Item: "Calibration Certificate",
        Qty: "55",
        Delivery: "26/02/2024",
        Company: "KS",
        UID: "Order-11",
        LeadDays: "120",
      },
      {
        Timestamp: "18/11/2024 08:20 AM",
        PONumber: "6700007899",
        Date: "1/11/2023",
        Yard: "",
        Org: "GSL",
        Item: "Hand held Anemometer with wind...",
        Qty: "2",
        Delivery: "27/02/2024",
        Company: "AE",
        UID: " Order-112",
        LeadDays: "120",
      },
      {
        Timestamp: "19/11/2024  5.35 PM",
        PONumber: "6700007905",
        Date: "3/11/2023",
        Yard: "",
        Org: "GRSE",
        Item: "MTC_Indian / Worid Meteor",
        Qty: " 5",
        Delivery: " 5/15/2024",
        Company: " AE",
        UID: " Order-113",
        LeadDays: "120",
      },
      {
        Timestamp: "21/11/2024  7.35 PM",
        PONumber: "6700007999",
        Date: "4/11/2023",
        Yard: "",
        Org: "GRSE",
        Item: "Digital Camera with SD Card",
        Qty: "7",
        Delivery: " 5/15/2024",
        Company: " KS",
        UID: " Order-116",
        LeadDays: "120",
      },
      {
        Timestamp: "23/11/2024  9.55 AM",
        PONumber: "6788888888",
        Date: "6-NOV-YYYY",
        Yard: "",
        Org: "GRSE",
        Item: "MTC_Indian / Worid Met   ",
        Qty: "   6   ",
        Delivery: "   5-DEC-YYYY   ",
        Company: " AE   ",
        UID: " Order-118   ",
        LeadDays: "120",
      },
    ],
  },

  {
    key: "step2",
    label: "Step 2",
    badge: 4,
    header: "P.O CHECK",
    columns: [
      { key: "poNumber", label: "PO Number" },
      { key: "company", label: "Company" },
      { key: "orderQty", label: "Order Qty" },
      { key: "orderItem", label: "Order Item" },
      { key: "planned", label: "Planned" },
      { key: "actual", label: "Actual" },
      { key: "status", label: "Status" },
      { key: "inspection", label: "Inspection" },
      { key: "doc", label: "Doc" },
      { key: "delDate", label: "Del Date" },
      { key: "gst", label: "GST" },
      { key: "hsn", label: "HSN" },
      { key: "qtyCheck", label: "Qty Check" },
      { key: "rate", label: "Rate" },
      { key: "itemCheck", label: "Item Check" },
      { key: "poAmd", label: "PO Amd" },
      { key: "link", label: "Link" },
      { key: "doer", label: "Doer" },
      { key: "delay", label: "Delay" },
      { key: "action", label: "Action" },
    ],
    data: [
      {
        poNumber: "6700006100",
        company: "AE",
        orderQty: 1,
        orderItem: "BINDING DATA_LAN_...",
        planned: "28/11/2024",
        actual: "-",
        status: "NOT DONE",
        inspection: "OKAY",
        doc: "OKAY",
        delDate: "OKAY",
        gst: "NOT OKAY",
        hsn: "NOT OKAY",
        qtyCheck: "OKAY",
        rate: "OKAY",
        itemCheck: "OKAY",
        poAmd: "YES",
        link: "-",
        doer: "Jayesh Kamdar",
        delay: "-",
        action: "Action",
      },
      {
        poNumber: "6700006100",
        company: "AE",
        orderQty: 1,
        orderItem: "TRAINING_LAN_ASEEC",
        planned: "28/11/2024",
        actual: "-",
        status: "NOT DONE",
        inspection: "OKAY",
        doc: "OKAY",
        delDate: "OKAY",
        gst: "NOT OKAY",
        hsn: "NOT OKAY",
        qtyCheck: "OKAY",
        rate: "OKAY",
        itemCheck: "OKAY",
        poAmd: "",
        link: "-",
        doer: "Jayesh Kamdar",
        delay: "-",
        action: "Action",
      },
      {
        poNumber: "6700006100",
        company: "AE",
        orderQty: 1,
        orderItem: "SERVICE OF ENGINEER...",
        planned: "28/11/2024",
        actual: "-",
        status: "NOT DONE",
        inspection: "OKAY",
        doc: "OKAY",
        delDate: "OKAY",
        gst: "NOT OKAY",
        hsn: "NOT OKAY",
        qtyCheck: "OKAY",
        rate: "OKAY",
        itemCheck: "OKAY",
        poAmd: "",
        link: "-",
        doer: "Jayesh Kamdar",
        delay: "-",
        action: "Action",
      },
      {
        poNumber: "6700006102",
        company: "AE",
        orderQty: 2,
        orderItem: "BATTERY BANK (6 NOS...)",
        planned: "28/11/2024",
        actual: "-",
        status: "NOT DONE",
        inspection: "OKAY",
        doc: "OKAY",
        delDate: "OKAY",
        gst: "NOT OKAY",
        hsn: "OKAY",
        qtyCheck: "OKAY",
        rate: "OKAY",
        itemCheck: "OKAY",
        poAmd: "YES",
        link: "-",
        doer: "Jayesh Kamdar",
        delay: "-",
        action: "Action",
      },
    ],
  },

  {
    key: "step3",
    label: "Step 3",
    badge: 2,
    header: "P.O ENTRY",
    columns: [
      { key: "id", label: "Offer ID", header: "P.O ENTRY", },
      { key: "name", label: "Candidate", header: "P.O ENTRY", },
      { key: "package", label: "Package", header: "P.O ENTRY", },
      { key: "joining", label: "Joining Date", header: "P.O ENTRY", },
    ],
    data: [{ id: 21, name: "Pooja", package: "8 LPA", joining: "1 Feb 2026" }],
  },

  {
    key: "step4",
    label: "Step 4",
    badge: 6,
    header: "DESPATCH DOC",
    columns: [
      { key: "id", label: "Verification ID" },
      { key: "name", label: "Candidate" },
      { key: "status", label: "Verification Status" },
      { key: "updated", label: "Last Updated" },
    ],
    data: [
      { id: 31, name: "Arjun", status: "Pending", updated: "2026-01-25" },
      { id: 32, name: "Sneha", status: "Completed", updated: "2026-01-26" },
    ],
  },

  {
    key: "step5",
    label: "Step 5",
    badge: 3,
    header: "PI MAKER",
    columns: [
      { key: "id", label: "Training ID" },
      { key: "name", label: "Candidate Name" },
      { key: "module", label: "Training Module" },
      { key: "status", label: "Status" },
    ],
    data: [
      { id: 41, name: "Ravi", module: "Safety", status: "In Progress" },
      { id: 42, name: "Anita", module: "Operations", status: "Completed" },
    ],
  },

  {
    key: "step6",
    label: "Step 6",
    badge: 15,
    header: "ORDER ISSUE",
    columns: [
      { key: "id", label: "Candidate ID" },
      { key: "name", label: "Candidate Name" },
      { key: "round", label: "Final Round" },
      { key: "date", label: "Final Interview Date" },
    ],
    data: [
      { id: 51, name: "Vikas", round: "Managerial", date: "2026-02-01" },
      { id: 52, name: "Priya", round: "Director", date: "2026-02-02" },
    ],
  },

  {
    key: "step7",
    label: "Step 7",
    badge: 8,
    header: "PI CHECKER",
    columns: [
      { key: "id", label: "Medical ID" },
      { key: "name", label: "Candidate Name" },
      { key: "hospital", label: "Hospital" },
      { key: "status", label: "Medical Status" },
    ],
    data: [
      { id: 61, name: "Rahul", hospital: "Apollo", status: "Fit" },
      { id: 62, name: "Meera", hospital: "AIIMS", status: "Pending" },
    ],
  },

  {
    key: "step8",
    label: "Step 8",
    badge: 12,
    header: "PAYMENT RELEASE",
    columns: [
      { key: "id", label: "Document ID" },
      { key: "name", label: "Candidate Name" },
      { key: "docType", label: "Document Type" },
      { key: "status", label: "Upload Status" },
    ],
    data: [
      { id: 71, name: "Aman", docType: "Aadhar", status: "Uploaded" },
      { id: 72, name: "Divya", docType: "PAN", status: "Pending" },
    ],
  },

  {
    key: "step9",
    label: "Step 9",
    badge: 5,
    header: "IN HOUSE RIC",
    columns: [
      { key: "id", label: "Onboarding ID" },
      { key: "name", label: "Employee Name" },
      { key: "department", label: "Department" },
      { key: "date", label: "Joining Date" },
    ],
    data: [
      { id: 81, name: "Sahil", department: "Operations", date: "2026-02-10" },
    ],
  },

  {
    key: "step10",
    label: "Step 10",
    badge: 9,
    header: "SALE BILL",
    columns: [
      { key: "id", label: "Probation ID" },
      { key: "name", label: "Employee Name" },
      { key: "period", label: "Probation Period" },
      { key: "status", label: "Status" },
    ],
    data: [{ id: 91, name: "Kriti", period: "3 Months", status: "Active" }],
  },

  {
    key: "step11",
    label: "Step 11",
    badge: 4,
    header: "DOC MAKER",
    columns: [
      { key: "id", label: "Review ID" },
      { key: "name", label: "Employee Name" },
      { key: "rating", label: "Performance Rating" },
      { key: "remarks", label: "Remarks" },
    ],
    data: [
      { id: 101, name: "Anil", rating: "4/5", remarks: "Good Performance" },
    ],
  },

  {
    key: "step12",
    label: "Step 12",
    badge: 7,
    header: "DOC CHECKER",
    columns: [
      { key: "id", label: "Confirmation ID" },
      { key: "name", label: "Employee Name" },
      { key: "status", label: "Confirmation Status" },
      { key: "date", label: "Confirmation Date" },
    ],
    data: [
      { id: 111, name: "Neeraj", status: "Confirmed", date: "2026-05-01" },
    ],
  },

  {
    key: "step13",
    label: "Step 13",
    badge: 2,
    header: "DELIVERY",
    columns: [
      { key: "id", label: "Promotion ID" },
      { key: "name", label: "Employee Name" },
      { key: "newRole", label: "New Role" },
      { key: "effective", label: "Effective Date" },
    ],
    data: [
      {
        id: 121,
        name: "Simran",
        newRole: "Team Lead",
        effective: "2026-06-01",
      },
    ],
  },

  {
    key: "step14",
    label: "Step 14",
    badge: 1,
    header: "HANDOVER EA",
    columns: [
      { key: "id", label: "Transfer ID" },
      { key: "name", label: "Employee Name" },
      { key: "location", label: "New Location" },
      { key: "date", label: "Transfer Date" },
    ],
    data: [{ id: 131, name: "Rohan", location: "Mumbai", date: "2026-07-15" }],
  },

  {
    key: "step15",
    label: "Step 15",
    badge: 0,
    header: "All Documents Received in Order",
    columns: [
      { key: "id", label: "Exit ID" },
      { key: "name", label: "Employee Name" },
      { key: "reason", label: "Exit Reason" },
      { key: "date", label: "Exit Date" },
    ],
    data: [{ id: 141, name: "Manish", reason: "Resigned", date: "2026-08-01" }],
  },
];
